# Generated by Django 5.2.6 on 2025-11-03 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_alter_processo_assunto_alter_processo_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='analisada_ia',
            field=models.BooleanField(default=False, help_text='Indica se esta movimentação foi analisada pela IA', verbose_name='Analisada por IA'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='analisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_analisadas', to=settings.AUTH_USER_MODEL, verbose_name='Analisada por'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='data_analise_ia',
            field=models.DateTimeField(blank=True, help_text='Quando a análise foi realizada', null=True, verbose_name='Data da Análise IA'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='resultado_analise_ia',
            field=models.JSONField(blank=True, help_text='Resultado completo da análise (prazos, audiências, etc.)', null=True, verbose_name='Resultado da Análise IA'),
        ),
    ]
